### PR TITLE
Add AngularJS webapp

### PR DESCRIPTION
**Pull request by hexylena**
## Changes

In `aRchive.py`:
- now we implement a single "bad_yaml_parser" to parse all of the package data.
- we dump the latest packages' information and a unique'd version list to `$outdir/api/$package_name.json`
- we dump a list of all packages to `$outdir/api/api.json`

In `reduce_versions.py`:
- the `_versions_full.txt` files are now transformed into `$outdir/api/$package_name/$version.json` json files. 
## TODO (at some later date):
- animations are a bit weird, need to replace with global package listing/menu and separate frame for just the package view

### CODE REVIEW

**Comment by nturaga** [comment]
@erasche This looks really nice!

**Comment by hexylena** [comment]
lol

**Comment by hexylena** [comment]
Sorry I didn't get around to adding https://github.com/angular-ui/ui-router during hackathon

**Comment by nturaga** [comment]
Haha, its cool. I just saw that it was still a PR. I'm going through my entire notifications today.

**Comment by hexylena** [comment]
Ah, did that yesterday. Absolutely massive list after just two sick-days.

**Pull request merged**
